const KEY="aideplanning_v1";let db=JSON.parse(localStorage.getItem(KEY)||'{"people":[],"visits":{}}'),month=new Date(),selected=new Date(),editVisit=null,editPerson=null;const $=x=>document.getElementById(x),pad=n=>String(n).padStart(2,"0"),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,uid=p=>p+Date.now()+Math.random().toString(36).slice(2),person=id=>db.people.find(p=>p.id===id),mins=t=>{let[a,b]=t.split(":").map(Number);return a*60+b},dur=(a,b)=>{let x=mins(a),y=mins(b);if(y<x)y+=1440;return y-x},fmt=m=>`${Math.floor(m/60)}h${pad(m%60)}`,save=()=>localStorage.setItem(KEY,JSON.stringify(db)),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(t){$("toast").textContent=t;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",1800)}
function monthVisits(){let p=`${month.getFullYear()}-${pad(month.getMonth()+1)}-`;return Object.entries(db.visits).filter(([d])=>d.startsWith(p)).flatMap(([date,v])=>v.map(x=>({...x,date})))}
function render(){renderCal();renderDay();renderPeople();renderStats()}
function renderCal(){let y=month.getFullYear(),m=month.getMonth(),mv=monthVisits(),total=mv.reduce((s,v)=>s+dur(v.start,v.end),0);$("month").textContent=month.toLocaleDateString("fr-FR",{month:"long",year:"numeric"});$("monthTotal").textContent=`${mv.length} visite${mv.length>1?"s":""} · ${fmt(total)}`;$("calendar").innerHTML="";let off=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();for(let i=0;i<off;i++)$("calendar").innerHTML+='<button class="day empty"></button>';for(let d=1;d<=days;d++){let dt=new Date(y,m,d),k=key(dt),v=db.visits[k]||[],t=v.reduce((s,x)=>s+dur(x.start,x.end),0),b=document.createElement("button");b.className="day"+(k===key(new Date())?" today":"")+(k===key(selected)?" selected":"")+(v.length?" has":"");b.innerHTML=`<b>${d}</b><span class="meta">${v.length?v.length+" visite"+(v.length>1?"s":"")+"<br>"+fmt(t):""}</span>`;b.onclick=()=>{selected=dt;render()};$("calendar").appendChild(b)}}
function renderDay(){let v=[...(db.visits[key(selected)]||[])].sort((a,b)=>a.start.localeCompare(b.start));$("dayTitle").textContent=selected.toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"});$("dayTotal").textContent=fmt(v.reduce((s,x)=>s+dur(x.start,x.end),0));$("visits").innerHTML=v.length?"":'<p>Aucune intervention.</p>';v.forEach(x=>{let b=document.createElement("button");b.className="visit";b.innerHTML=`<span><h3>${esc(person(x.personId)?.name||"Personne supprimée")}</h3><b>${x.start} → ${x.end}</b>${x.note?`<p>${esc(x.note)}</p>`:""}</span><strong>${fmt(dur(x.start,x.end))}</strong>`;b.onclick=()=>openVisit(x.id);$("visits").appendChild(b)})}
function renderPeople(){let q=$("search").value.toLowerCase(),list=$("peopleList");list.innerHTML="";db.people.filter(p=>(p.name+p.address+p.phone).toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name)).forEach(p=>{let a=document.createElement("article");a.className="person";a.innerHTML=`<h3>${esc(p.name)}</h3><p>${p.address?"📍 "+esc(p.address)+"<br>":""}${p.phone?"📞 "+esc(p.phone)+"<br>":""}${p.notes?esc(p.notes):""}</p><button>Modifier</button>`;a.querySelector("button").onclick=()=>openPerson(p.id);list.appendChild(a)});if(!list.children.length)list.innerHTML='<div class="card"><p>Aucun bénéficiaire enregistré.</p></div>'}
function renderStats(){let mv=monthVisits(),total=mv.reduce((s,v)=>s+dur(v.start,v.end),0);$("statsTitle").textContent="Résumé — "+month.toLocaleDateString("fr-FR",{month:"long",year:"numeric"});$("sHours").textContent=fmt(total);$("sVisits").textContent=mv.length;$("sPeople").textContent=new Set(mv.map(v=>v.personId)).size;$("sDays").textContent=new Set(mv.map(v=>v.date)).size;let t={};mv.forEach(v=>t[v.personId]=(t[v.personId]||0)+dur(v.start,v.end));$("personStats").innerHTML=Object.entries(t).sort((a,b)=>b[1]-a[1]).map(([id,m])=>`<div class="personStat"><span>${esc(person(id)?.name||"Supprimé")}</span><strong>${fmt(m)}</strong></div>`).join("")||"<p>Aucune donnée ce mois-ci.</p>"}
function openVisit(id){if(!db.people.length){toast("Ajoutez d’abord un bénéficiaire");show("people");return}editVisit=id;let v=(db.visits[key(selected)]||[]).find(x=>x.id===id);$("visitDlgTitle").textContent=v?"Modifier l’intervention":"Ajouter une intervention";$("visitPerson").innerHTML='<option value="">Choisir</option>'+db.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");$("visitPerson").value=v?.personId||"";$("start").value=v?.start||"08:00";$("end").value=v?.end||"09:00";$("visitNote").value=v?.note||"";$("deleteVisit").style.display=v?"block":"none";$("visitDlg").showModal()}
function openPerson(id){editPerson=id;let p=person(id);$("personDlgTitle").textContent=p?"Modifier le bénéficiaire":"Ajouter un bénéficiaire";$("personName").value=p?.name||"";$("address").value=p?.address||"";$("phone").value=p?.phone||"";$("notes").value=p?.notes||"";$("deletePerson").style.display=p?"block":"none";$("personDlg").showModal()}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id))}
$("visitForm").onsubmit=e=>{e.preventDefault();let k=key(selected),v={personId:$("visitPerson").value,start:$("start").value,end:$("end").value,note:$("visitNote").value};db.visits[k]??=[];if(editVisit){let i=db.visits[k].findIndex(x=>x.id===editVisit);db.visits[k][i]={...db.visits[k][i],...v}}else db.visits[k].push({id:uid("v"),...v});save();$("visitDlg").close();render();toast("Intervention enregistrée")};
$("personForm").onsubmit=e=>{e.preventDefault();let v={name:$("personName").value,address:$("address").value,phone:$("phone").value,notes:$("notes").value};if(editPerson){let i=db.people.findIndex(x=>x.id===editPerson);db.people[i]={...db.people[i],...v}}else db.people.push({id:uid("p"),...v});save();$("personDlg").close();render();toast("Bénéficiaire enregistré")};
$("deleteVisit").onclick=()=>{let k=key(selected);db.visits[k]=db.visits[k].filter(x=>x.id!==editVisit);if(!db.visits[k].length)delete db.visits[k];save();$("visitDlg").close();render()};
$("deletePerson").onclick=()=>{if(!confirm("Supprimer cette personne et ses interventions ?"))return;db.people=db.people.filter(x=>x.id!==editPerson);Object.keys(db.visits).forEach(k=>{db.visits[k]=db.visits[k].filter(v=>v.personId!==editPerson);if(!db.visits[k].length)delete db.visits[k]});save();$("personDlg").close();render()};
$("addVisit").onclick=()=>openVisit();$("addPerson").onclick=()=>openPerson();$("search").oninput=renderPeople;$("prev").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);selected=new Date(month);render()};$("next").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);selected=new Date(month);render()};$("today").onclick=()=>{month=new Date();selected=new Date();show("planning");render()};$("duplicate").onclick=()=>{let src=db.visits[key(selected)]||[];if(!src.length)return toast("Journée vide");let dest=prompt("Date de destination (AAAA-MM-JJ)",key(new Date(selected.getFullYear(),selected.getMonth(),selected.getDate()+1)));if(!dest)return;db.visits[dest]=[...(db.visits[dest]||[]),...src.map(v=>({...v,id:uid("v") }))];save();render();toast("Journée dupliquée")};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll(".close").forEach(b=>b.onclick=()=>b.closest("dialog").close());
function download(content,name,type){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([content],{type}));a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
$("csv").onclick=()=>{let r=[["Date","Bénéficiaire","Entrée","Sortie","Durée","Note"]];monthVisits().forEach(v=>r.push([v.date,person(v.personId)?.name||"",v.start,v.end,fmt(dur(v.start,v.end)),v.note]));download("\ufeff"+r.map(x=>x.map(c=>`"${String(c).replaceAll('"','""')}"`).join(";")).join("\n"),"aideplanning.csv","text/csv")};
$("backup").onclick=()=>download(JSON.stringify(db,null,2),"aideplanning-sauvegarde.json","application/json");
$("restore").onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!x.people||!x.visits)throw 0;if(confirm("Remplacer les données actuelles ?")){db=x;save();render();toast("Sauvegarde restaurée")}}catch{toast("Fichier invalide")}};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));render();